// Fetch and bundle web fonts locally so the packaged app never touches the
// network for typography. Downloads Zen Maru Gothic (500/700) and JetBrains
// Mono (400/500/600/700) woff2 subsets from the Google Fonts CSS API, writes
// them to src/renderer/assets/fonts/ with deterministic names, and generates
// src/renderer/styles/fonts.css with the same @font-face blocks pointing at
// the local files. Run once with `bun scripts/fetch-fonts.mjs`; the artifacts
// are committed.
import { mkdir, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import path from 'node:path';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const FONTS_DIR = path.join(ROOT, 'src', 'renderer', 'assets', 'fonts');
const CSS_OUT = path.join(ROOT, 'src', 'renderer', 'styles', 'fonts.css');

// css2 endpoint; a modern Chrome UA makes Google return woff2 with
// unicode-range subsets instead of a single legacy ttf.
const CSS_URL =
  'https://fonts.googleapis.com/css2' +
  '?family=Zen+Maru+Gothic:wght@500;700' +
  '&family=JetBrains+Mono:wght@400;500;600;700' +
  '&display=swap';

const USER_AGENT =
  'Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) ' +
  'Chrome/126.0.0.0 Safari/537.36';

const CONCURRENCY = 8;

function slugify(family) {
  return family.toLowerCase().replace(/[^a-z0-9]+/g, '-').replace(/^-|-$/g, '');
}

function prop(block, name) {
  const m = block.match(new RegExp(`${name}\\s*:\\s*([^;]+);`));
  return m ? m[1].trim() : null;
}

async function main() {
  console.log(`Fetching font CSS: ${CSS_URL}`);
  let css;
  try {
    const res = await fetch(CSS_URL, { headers: { 'User-Agent': USER_AGENT } });
    if (!res.ok) throw new Error(`HTTP ${res.status} ${res.statusText}`);
    css = await res.text();
  } catch (err) {
    console.error(`FATAL: could not fetch Google Fonts CSS: ${err.message}`);
    process.exit(1);
  }

  const blocks = css.match(/@font-face\s*\{[^}]*\}/g) ?? [];
  if (blocks.length === 0) {
    console.error('FATAL: no @font-face blocks found in the fetched CSS.');
    process.exit(1);
  }
  console.log(`Parsed ${blocks.length} @font-face blocks.`);

  const subsetCounters = new Map(); // "family-weight" -> next subset index
  const faces = [];
  for (const block of blocks) {
    const familyRaw = prop(block, 'font-family');
    const weight = prop(block, 'font-weight');
    const style = prop(block, 'font-style') ?? 'normal';
    const display = prop(block, 'font-display') ?? 'swap';
    const unicodeRange = prop(block, 'unicode-range');
    const src = prop(block, 'src');
    if (!familyRaw || !weight || !src) {
      console.error(`FATAL: malformed @font-face block:\n${block}`);
      process.exit(1);
    }
    const urlMatch = src.match(/url\((https:[^)]+\.woff2)\)/);
    if (!urlMatch) {
      console.error(`FATAL: no woff2 url in src (got: ${src}). ` +
        'The CSS API likely served a non-woff2 response; check the User-Agent.');
      process.exit(1);
    }
    const family = familyRaw.replace(/^['"]|['"]$/g, '');
    const key = `${slugify(family)}-${weight}`;
    const n = (subsetCounters.get(key) ?? 0) + 1;
    subsetCounters.set(key, n);
    faces.push({
      family,
      weight,
      style,
      display,
      unicodeRange,
      remoteUrl: urlMatch[1],
      fileName: `${key}-subset${n}.woff2`,
    });
  }

  await mkdir(FONTS_DIR, { recursive: true });

  let downloaded = 0;
  let totalBytes = 0;
  const queue = [...faces];
  async function worker() {
    for (;;) {
      const face = queue.shift();
      if (!face) return;
      const res = await fetch(face.remoteUrl, { headers: { 'User-Agent': USER_AGENT } });
      if (!res.ok) {
        throw new Error(`HTTP ${res.status} downloading ${face.remoteUrl}`);
      }
      const buf = Buffer.from(await res.arrayBuffer());
      await writeFile(path.join(FONTS_DIR, face.fileName), buf);
      downloaded += 1;
      totalBytes += buf.length;
      if (downloaded % 50 === 0) console.log(`  ${downloaded}/${faces.length} files...`);
    }
  }
  try {
    await Promise.all(Array.from({ length: CONCURRENCY }, worker));
  } catch (err) {
    console.error(`FATAL: font download failed: ${err.message}`);
    process.exit(1);
  }
  console.log(`Downloaded ${downloaded} woff2 files (${(totalBytes / 1024 / 1024).toFixed(1)} MiB).`);

  const header =
    '/* Generated by scripts/fetch-fonts.mjs. Do not edit by hand.\n' +
    ' * Zen Maru Gothic 500/700 + JetBrains Mono 400/500/600/700, bundled\n' +
    ' * locally as unicode-range woff2 subsets; runtime never hits the network. */\n';
  const out = faces.map((f) => {
    const lines = [
      '@font-face {',
      `  font-family: '${f.family}';`,
      `  font-style: ${f.style};`,
      `  font-weight: ${f.weight};`,
      `  font-display: ${f.display};`,
      `  src: url(../assets/fonts/${f.fileName}) format('woff2');`,
    ];
    if (f.unicodeRange) lines.push(`  unicode-range: ${f.unicodeRange};`);
    lines.push('}');
    return lines.join('\n');
  });
  await writeFile(CSS_OUT, `${header}\n${out.join('\n\n')}\n`);
  console.log(`Wrote ${path.relative(ROOT, CSS_OUT)} with ${faces.length} @font-face blocks.`);
}

await main();
